<?php
require __DIR__ . '/../auth/config.php';

$pdo = get_database_connection();
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

function ok(string $message): void {
    echo "OK   $message\n";
}

function fail(string $message): void {
    fwrite(STDERR, "FAIL $message\n");
    exit(1);
}

function assert_true($condition, string $message): void {
    if (!$condition) {
        fail($message);
    }
    ok($message);
}

function constraint_exists(PDO $pdo, string $name): bool {
    $stmt = $pdo->prepare('SELECT 1 FROM pg_constraint WHERE conname = :name');
    $stmt->execute([':name' => $name]);
    return (bool)$stmt->fetchColumn();
}

function index_exists(PDO $pdo, string $name): bool {
    $stmt = $pdo->prepare('SELECT 1 FROM pg_class WHERE relname = :name AND relkind = \'i\'');
    $stmt->execute([':name' => $name]);
    return (bool)$stmt->fetchColumn();
}

assert_true(constraint_exists($pdo, 'news_pkey'), 'news primary key exists');
assert_true(constraint_exists($pdo, 'pendingsubmission_pkey'), 'pendingsubmission primary key exists');
assert_true(constraint_exists($pdo, 'pendingsubmission_status_check'), 'pendingsubmission status check exists');

assert_true(index_exists($pdo, 'news_created_at_id_desc_idx'), 'news timeline index exists');
assert_true(index_exists($pdo, 'pendingsubmission_status_submitted_idx'), 'pending status/submitted index exists');
assert_true(index_exists($pdo, 'pendingsubmission_map_vehicle_idx'), 'pending map/vehicle index exists');

$newsCount = (int)$pdo->query('SELECT COUNT(*) FROM news')->fetchColumn();
$legacyNewsCount = (int)$pdo->query('SELECT COUNT(*) FROM _news')->fetchColumn();
assert_true($newsCount >= $legacyNewsCount, 'news table contains migrated legacy rows');

$pendingCount = (int)$pdo->query('SELECT COUNT(*) FROM pendingsubmission')->fetchColumn();
$legacyPendingCount = (int)$pdo->query('SELECT COUNT(*) FROM _pendingsubmission')->fetchColumn();
assert_true($pendingCount >= $legacyPendingCount, 'pendingsubmission table contains migrated legacy rows');

$pdo->beginTransaction();
try {
    $newsStmt = $pdo->prepare('INSERT INTO news (title, content, author) VALUES (:title, :content, :author) RETURNING id, created_at');
    $newsStmt->execute([
        ':title' => 'Integrity Test News ' . time(),
        ':content' => 'Validation row for canonical table constraints.',
        ':author' => 'integrity-check',
    ]);
    $newsRow = $newsStmt->fetch(PDO::FETCH_ASSOC);
    assert_true((int)$newsRow['id'] > 0, 'news id generated by sequence');
    assert_true(!empty($newsRow['created_at']), 'news created_at default applied');

    $pendingStmt = $pdo->prepare('INSERT INTO pendingsubmission (idmap, idvehicle, distance, playername, playercountry, submitterip, tuningparts) VALUES (:idmap, :idvehicle, :distance, :playername, :playercountry, :submitterip, :tuningparts) RETURNING id, status, submitted_at');
    $pendingStmt->execute([
        ':idmap' => 1,
        ':idvehicle' => 1,
        ':distance' => 12345,
        ':playername' => 'Integrity Runner',
        ':playercountry' => 'Testland',
        ':submitterip' => '127.0.0.1',
        ':tuningparts' => 'Wings, Magnet',
    ]);
    $pendingRow = $pendingStmt->fetch(PDO::FETCH_ASSOC);
    assert_true((int)$pendingRow['id'] > 0, 'pending submission id generated');
    assert_true($pendingRow['status'] === 'pending', 'pending submission status default applied');
    assert_true(!empty($pendingRow['submitted_at']), 'pending submission timestamp default applied');
} finally {
    $pdo->rollBack();
}

echo "Canonical table integrity tests completed.\n";
