<?php
require __DIR__ . '/../auth/config.php';

$pdo = get_database_connection();
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

function ok(string $message): void {
    echo "OK   $message\n";
}

function fail(string $message): void {
    fwrite(STDERR, "FAIL $message\n");
    exit(1);
}

function assert_true($condition, string $message): void {
    if (!$condition) {
        fail($message);
    }
    ok($message);
}

function constraint_exists(PDO $pdo, string $name): bool {
    $stmt = $pdo->prepare('SELECT 1 FROM pg_constraint WHERE conname = :name');
    $stmt->execute([':name' => $name]);
    return (bool)$stmt->fetchColumn();
}

function index_exists(PDO $pdo, string $name): bool {
    $stmt = $pdo->prepare('SELECT 1 FROM pg_class WHERE relname = :name AND relkind = \'i\'');
    $stmt->execute([':name' => $name]);
    return (bool)$stmt->fetchColumn();
}

foreach ([
    'map_pkey',
    'vehicle_pkey',
    'player_pkey',
    'tuning_part_pkey',
    'tuning_setup_pkey',
    'tuning_setup_part_pkey',
    'world_record_pkey',
    'world_record_map_fk',
    'world_record_vehicle_fk',
    'world_record_player_fk',
    'world_record_tuning_setup_fk',
    'tuning_setup_part_setup_fk',
    'tuning_setup_part_part_fk',
] as $constraint) {
    assert_true(constraint_exists($pdo, $constraint), "constraint exists: $constraint");
}
assert_true(index_exists($pdo, 'world_record_current_map_vehicle_unique'), 'partial unique index exists for current records');

$pdo->beginTransaction();
try {
    $suffix = 'DryRun' . time();

    $stmt = $pdo->prepare('INSERT INTO map (name_map, special) VALUES (:name, 0) RETURNING id_map');
    $stmt->execute([':name' => 'Map' . substr($suffix, -8)]);
    $mapId = (int)$stmt->fetchColumn();

    $stmt = $pdo->prepare('INSERT INTO vehicle (name_vehicle) VALUES (:name) RETURNING id_vehicle');
    $stmt->execute([':name' => 'Veh' . substr($suffix, -8)]);
    $vehicleId = (int)$stmt->fetchColumn();

    $stmt = $pdo->prepare('INSERT INTO player (name_player, country) VALUES (:name, :country) RETURNING id_player');
    $stmt->execute([':name' => 'P' . substr($suffix, -8), ':country' => 'Testland']);
    $playerId = (int)$stmt->fetchColumn();

    $stmt = $pdo->prepare('INSERT INTO tuning_part (name_tuning_part) VALUES (:name) RETURNING id_tuning_part');
    $stmt->execute([':name' => 'Part' . substr($suffix, -8)]);
    $partId = (int)$stmt->fetchColumn();

    $stmt = $pdo->prepare('INSERT INTO tuning_setup DEFAULT VALUES RETURNING id_tuning_setup');
    $stmt->execute();
    $setupId = (int)$stmt->fetchColumn();

    $stmt = $pdo->prepare('INSERT INTO tuning_setup_part (id_tuning_setup, id_tuning_part) VALUES (:setup, :part)');
    $stmt->execute([':setup' => $setupId, ':part' => $partId]);

    $stmt = $pdo->prepare('INSERT INTO world_record (id_map, id_vehicle, id_player, distance, current, id_tuning_setup, questionable) VALUES (:map, :vehicle, :player, 12345, 1, :setup, 0) RETURNING id_record');
    $stmt->execute([':map' => $mapId, ':vehicle' => $vehicleId, ':player' => $playerId, ':setup' => $setupId]);
    $recordId = (int)$stmt->fetchColumn();
    assert_true($recordId > 0, 'world_record id_record generated by sequence');

    try {
        $pdo->exec('SAVEPOINT duplicate_current_check');
        $stmt->execute([':map' => $mapId, ':vehicle' => $vehicleId, ':player' => $playerId, ':setup' => $setupId]);
        fail('duplicate current record should be blocked');
    } catch (PDOException $e) {
        $pdo->exec('ROLLBACK TO SAVEPOINT duplicate_current_check');
        assert_true($e->getCode() === '23505', 'duplicate current record blocked by unique constraint');
    }

    try {
        $pdo->exec('SAVEPOINT invalid_fk_check');
        $bad = $pdo->prepare('INSERT INTO world_record (id_map, id_vehicle, id_player, distance, current) VALUES (-999, :vehicle, :player, 1, 1)');
        $bad->execute([':vehicle' => $vehicleId, ':player' => $playerId]);
        fail('invalid FK insert should be blocked');
    } catch (PDOException $e) {
        $pdo->exec('ROLLBACK TO SAVEPOINT invalid_fk_check');
        assert_true($e->getCode() === '23503', 'invalid FK insert blocked');
    }

    try {
        $pdo->exec('SAVEPOINT referenced_delete_check');
        $pdo->prepare('DELETE FROM map WHERE id_map = :id')->execute([':id' => $mapId]);
        fail('referenced map deletion should be blocked');
    } catch (PDOException $e) {
        $pdo->exec('ROLLBACK TO SAVEPOINT referenced_delete_check');
        assert_true($e->getCode() === '23503', 'referenced map deletion blocked');
    }

    $stmt = $pdo->prepare('INSERT INTO pending_submission (id_map, id_vehicle, distance, player_name, player_country, tuning_parts, submitter_ip) VALUES (:map, :vehicle, 54321, :player, :country, :parts, :ip) RETURNING id, status');
    $stmt->execute([
        ':map' => $mapId,
        ':vehicle' => $vehicleId,
        ':player' => 'Pending ' . $suffix,
        ':country' => 'Testland',
        ':parts' => 'Wings, Nitro, Magnet',
        ':ip' => '127.0.0.1',
    ]);
    $pending = $stmt->fetch(PDO::FETCH_ASSOC);
    assert_true((int)$pending['id'] > 0 && $pending['status'] === 'pending', 'pending submission id/default status generated');

    $pdo->prepare('UPDATE pending_submission SET status = :status WHERE id = :id')->execute([':status' => 'approved', ':id' => $pending['id']]);
    $status = $pdo->query('SELECT status FROM pending_submission WHERE id = ' . (int)$pending['id'])->fetchColumn();
    assert_true($status === 'approved', 'pending submission transition works');
} finally {
    $pdo->rollBack();
}

echo "Post-migration integrity tests completed.\n";
