CREATE TABLE _map (
    idmap integer PRIMARY KEY,
    namemap text NOT NULL UNIQUE,
    special integer NOT NULL DEFAULT 0,
    "idMap" integer GENERATED ALWAYS AS (idmap) STORED,
    "nameMap" text GENERATED ALWAYS AS (namemap) STORED
);

CREATE TABLE _vehicle (
    idvehicle integer PRIMARY KEY,
    namevehicle text NOT NULL UNIQUE,
    "idVehicle" integer GENERATED ALWAYS AS (idvehicle) STORED,
    "nameVehicle" text GENERATED ALWAYS AS (namevehicle) STORED
);

CREATE TABLE _player (
    idplayer integer PRIMARY KEY,
    nameplayer text NOT NULL,
    country text,
    "idPlayer" integer GENERATED ALWAYS AS (idplayer) STORED,
    "namePlayer" text GENERATED ALWAYS AS (nameplayer) STORED
);

CREATE TABLE _tuningpart (
    idtuningpart integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nametuningpart text NOT NULL UNIQUE,
    "idTuningPart" integer GENERATED ALWAYS AS (idtuningpart) STORED,
    "nameTuningPart" text GENERATED ALWAYS AS (nametuningpart) STORED
);

CREATE TABLE _tuningsetup (
    idtuningsetup integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "idTuningSetup" integer GENERATED ALWAYS AS (idtuningsetup) STORED
);

CREATE TABLE _tuningsetupparts (
    idtuningsetup integer NOT NULL REFERENCES _tuningsetup(idtuningsetup) ON DELETE CASCADE,
    idtuningpart integer NOT NULL REFERENCES _tuningpart(idtuningpart) ON DELETE RESTRICT,
    "idTuningSetup" integer GENERATED ALWAYS AS (idtuningsetup) STORED,
    "idTuningPart" integer GENERATED ALWAYS AS (idtuningpart) STORED,
    PRIMARY KEY (idtuningsetup, idtuningpart)
);

CREATE TABLE _worldrecord (
    idrecord integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idmap integer NOT NULL REFERENCES _map(idmap) ON DELETE RESTRICT,
    idvehicle integer NOT NULL REFERENCES _vehicle(idvehicle) ON DELETE RESTRICT,
    idplayer integer REFERENCES _player(idplayer) ON DELETE SET NULL,
    distance integer NOT NULL CHECK (distance > 0),
    current integer NOT NULL DEFAULT 1 CHECK (current IN (0, 1)),
    idtuningsetup integer REFERENCES _tuningsetup(idtuningsetup) ON DELETE SET NULL,
    questionable integer NOT NULL DEFAULT 0 CHECK (questionable IN (0, 1)),
    questionable_reason text,
    "idRecord" integer GENERATED ALWAYS AS (idrecord) STORED,
    "idMap" integer GENERATED ALWAYS AS (idmap) STORED,
    "idVehicle" integer GENERATED ALWAYS AS (idvehicle) STORED,
    "idPlayer" integer GENERATED ALWAYS AS (idplayer) STORED,
    "idTuningSetup" integer GENERATED ALWAYS AS (idtuningsetup) STORED
);

CREATE INDEX idx_worldrecord_current ON _worldrecord(current);
CREATE INDEX idx_worldrecord_map_vehicle ON _worldrecord(idmap, idvehicle);

CREATE TABLE pendingsubmission (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idmap integer REFERENCES _map(idmap) ON DELETE SET NULL,
    idvehicle integer REFERENCES _vehicle(idvehicle) ON DELETE SET NULL,
    distance integer CHECK (distance IS NULL OR distance > 0),
    playername text,
    playercountry text,
    submitterip text,
    status text NOT NULL DEFAULT 'pending',
    submitted_at timestamptz NOT NULL DEFAULT now(),
    tuningparts text,
    "idMap" integer GENERATED ALWAYS AS (idmap) STORED,
    "idVehicle" integer GENERATED ALWAYS AS (idvehicle) STORED,
    "playerName" text GENERATED ALWAYS AS (playername) STORED,
    "playerCountry" text GENERATED ALWAYS AS (playercountry) STORED,
    "submitterIp" text GENERATED ALWAYS AS (submitterip) STORED,
    "tuningParts" text GENERATED ALWAYS AS (tuningparts) STORED
);

CREATE INDEX idx_pending_status_submitted ON pendingsubmission(status, submitted_at DESC);
CREATE INDEX idx_pending_submitter_time ON pendingsubmission(submitterip, submitted_at);

CREATE TABLE news (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    content text NOT NULL,
    author text,
    created_at timestamptz NOT NULL DEFAULT now()
);
